// Generated by Corvo Transpiler
#[allow(unused_imports)]
use corvo_lang::type_system::Value;
use corvo_lang::RuntimeState;
use corvo_lang::CorvoError;
use corvo_lang::ast::AssertKind;
use std::collections::HashMap;

fn main() {
    match run() {
        Ok(_) => {},
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(e.exit_code());
        }
    }
}

fn run() -> Result<(), CorvoError> {
    let mut state = RuntimeState::new();
    state.set_script_argv(std::env::args().skip(1).collect());

    state.var_set("hash".to_string(), corvo_lang::standard_lib::call("crypto.hash", &[Value::String("md5".to_string()), Value::String("hello".to_string())], &HashMap::new(), &state)?);
    corvo_lang::standard_lib::call("sys.echo", &[state.var_get("hash")?], &HashMap::new(), &state)?;
    Ok(())
}
