// Generated by Corvo Transpiler
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::never_loop)]
#![allow(clippy::useless_vec)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::collapsible_else_if)]
#![allow(clippy::needless_if)]
#![allow(clippy::if_same_then_else)]
#![allow(clippy::len_zero)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(unreachable_code)]
use corvo_lang::type_system::Value;
use corvo_lang::RuntimeState;
use corvo_lang::CorvoError;
use corvo_lang::ast::AssertKind;
use corvo_lang::*;
use std::collections::HashMap;

fn main() {
    match run() {
        Ok(_) => {},
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(e.exit_code());
        }
    }
}

fn run() -> Result<(), CorvoError> {
    let mut state = RuntimeState::new();
    state.set_script_argv(std::env::args().skip(1).collect());

    {
        let val = Value::List(vec![Value::Number(1.0), Value::Number(2.0), Value::Number(3.0), Value::Number(4.0), Value::Number(5.0)]);
        state.var_set("nums".to_string(), val);
    }
    {
        let val = Value::Number(0.0);
        state.var_set("sum".to_string(), val);
    }
    {
        let val = Value::NativeProcedure {
    params: vec!["item".to_string(), "s".to_string()],
    callback: std::sync::Arc::new(|args: &[Value], mut state: &mut RuntimeState| {
    if args.len() < 2 { return Err(CorvoError::runtime(format!("Procedure expects at least 2 arguments, got {}", args.len()))); }
    state.var_set("item".to_string(), args[0].clone());
    state.var_set("s".to_string(), args[1].clone());
    {
        let val = corvo_lang::math_add!(&state, state.var_get("s")?, state.var_get("item")?)?;
        state.var_set("s".to_string(), val);
    }
    Ok(Value::Null)
}),
};
        state.var_set("worker".to_string(), val);
    }
    corvo_lang::compiler::Evaluator::new().exec_async_browse_native(
        match state.var_get("nums")? { Value::List(l) => l, _ => return Err(CorvoError::r#type("async_browse requires a list")) },
        match state.var_get("worker")? { Value::NativeProcedure { params: ref p, .. } => p.clone(), _ => return Err(CorvoError::r#type("async_browse expects a procedure")) },
        match state.var_get("worker")? { Value::NativeProcedure { callback: ref p, .. } => p.clone(), _ => return Err(CorvoError::r#type("async_browse expects a procedure")) },
        "item",
        &["sum".to_string()],
        &mut state
    )?;
    corvo_lang::sys_echo!(&state, state.var_get("sum")?)?;
    Ok(())
}
