// Generated by Corvo Transpiler
#[allow(unused_imports)]
use type_system::Value;
use RuntimeState;
use CorvoError;
use ast::AssertKind;
use std::collections::HashMap;

fn main() {
    match run() {
        Ok(_) => {},
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(e.exit_code());
        }
    }
}

fn run() -> Result<(), CorvoError> {
    let mut state = RuntimeState::new();
    state.set_script_argv(std::env::args().skip(1).collect());

    state.var_set("nums".to_string(), Value::List(vec![Value::Number(1.0), Value::Number(2.0), Value::Number(3.0), Value::Number(4.0), Value::Number(5.0)]));
    state.var_set("sum".to_string(), Value::Number(0.0));
    state.var_set("worker".to_string(), Value::NativeProcedure {
    params: vec!["item".to_string(), "s".to_string()],
    callback: std::sync::Arc::new(|args: &[Value], state: &mut RuntimeState| {
    if args.len() < 2 { return Err(CorvoError::runtime(format!("Procedure expects at least 2 arguments, got {}", args.len()))); }
    state.var_set("item".to_string(), args[0].clone());
    state.var_set("s".to_string(), args[1].clone());
    state.var_set("s".to_string(), math_add!(&state, state.var_get("s")?, state.var_get("item")?)?);
    Ok(Value::Null)
}),
});
    compiler::Evaluator::new().exec_async_browse_native(
        match state.var_get("nums")? { Value::List(l) => l, _ => return Err(CorvoError::r#type("async_browse requires a list")) },
        match state.var_get("worker")? { Value::NativeProcedure { params: ref p, .. } => p.clone(), _ => return Err(CorvoError::r#type("async_browse expects a procedure")) },
        match state.var_get("worker")? { Value::NativeProcedure { callback: ref p, .. } => p.clone(), _ => return Err(CorvoError::r#type("async_browse expects a procedure")) },
        "item",
        &["sum".to_string()],
        &mut state
    )?;
    sys_echo!(&state, state.var_get("sum")?)?;
    Ok(())
}
