use crate::ast::Program;
use crate::compiler::transpiler::Transpiler;
use crate::compiler::usage_analyzer::UsageAnalysis;
use crate::type_system::Value;
use std::collections::HashMap;

/// The Oxide transpiler generates lean Rust code with direct function calls to
/// `corvo_lang::standard_lib::*` instead of routing through macro-based dispatch.
/// Combined with feature-gated dependencies, this produces significantly smaller binaries.
///
/// Internally delegates to `Transpiler` (with `oxide_mode` enabled) for all
/// statement and expression transpilation.
pub struct OxideTranspiler {
    pub captured_statics: HashMap<String, Value>,
    /// Usage analysis from the source AST — drives selective imports.
    usage: UsageAnalysis,
}

impl OxideTranspiler {
    pub fn new(usage: UsageAnalysis) -> Self {
        Self {
            captured_statics: HashMap::new(),
            usage,
        }
    }

    pub fn with_statics(mut self, statics: HashMap<String, Value>) -> Self {
        self.captured_statics = statics;
        self
    }

    /// Transpile the program to Rust source code using the Oxide mode.
    pub fn transpile(&self, program: &Program) -> String {
        // Build a Transpiler in oxide mode so it generates direct stdlib calls.
        let transpiler = Transpiler::default()
            .with_statics(self.captured_statics.clone())
            .with_oxide_mode();

        // Generate the body using the oxide-enabled transpiler.
        let body = transpiler.transpile_oxide_body(program);

        let mut rust_code = String::new();
        rust_code.push_str("// Generated by Corvo Oxide Transpiler\n");
        rust_code.push_str("#![allow(clippy::redundant_closure_call)]\n");
        rust_code.push_str("#![allow(clippy::needless_borrow)]\n");
        rust_code.push_str("#![allow(clippy::never_loop)]\n");
        rust_code.push_str("#![allow(clippy::useless_vec)]\n");
        rust_code.push_str("#![allow(clippy::collapsible_if)]\n");
        rust_code.push_str("#![allow(clippy::collapsible_else_if)]\n");
        rust_code.push_str("#![allow(clippy::needless_if)]\n");
        rust_code.push_str("#![allow(clippy::if_same_then_else)]\n");
        rust_code.push_str("#![allow(clippy::len_zero)]\n");
        rust_code.push_str("#![allow(unused_mut)]\n");
        rust_code.push_str("#![allow(unused_imports)]\n");
        rust_code.push_str("#![allow(unreachable_code)]\n");

        // Selective imports — only the namespaces actually used
        rust_code.push_str("use corvo_lang::type_system::Value;\n");
        rust_code.push_str("use corvo_lang::RuntimeState;\n");
        rust_code.push_str("use corvo_lang::CorvoError;\n");
        rust_code.push_str("use corvo_lang::ast::AssertKind;\n");
        rust_code.push_str("use std::collections::HashMap;\n");
        // Always import standard_lib (for regex in match expressions, etc.)
        rust_code.push_str("use corvo_lang::standard_lib;\n");

        // Type method namespaces (string, number, list, map, re) don't exist as
        // standard_lib modules — they go through type_methods which is called by
        // full path. Only import real stdlib modules.
        let type_method_ns = ["string", "number", "list", "map", "re"];
        for ns in &self.usage.namespaces {
            if !type_method_ns.contains(&ns.as_str()) {
                rust_code.push_str(&format!("use corvo_lang::standard_lib::{};\n", ns));
            }
        }

        rust_code.push('\n');
        rust_code.push_str(&body);
        rust_code
    }
}
