use crate::ast::{AssertKind, BinaryOp, Expr, MatchPattern, Program, Stmt, UnaryOp};
use crate::type_system::Value;
use std::collections::HashMap;

pub struct Transpiler {
    pub indent_level: usize,
    pub captured_statics: HashMap<String, Value>,
    pub closure_depth: usize,
}

impl Transpiler {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for Transpiler {
    fn default() -> Self {
        Self {
            indent_level: 1,
            captured_statics: HashMap::new(),
            closure_depth: 0,
        }
    }
}

impl Transpiler {
    pub fn with_statics(mut self, statics: HashMap<String, Value>) -> Self {
        self.captured_statics = statics;
        self
    }

    pub fn transpile(mut self, program: &Program) -> String {
        let mut rust_code = String::new();
        rust_code.push_str("// Generated by Corvo Transpiler\n");
        rust_code.push_str("#![allow(clippy::redundant_closure_call)]\n");
        rust_code.push_str("#![allow(clippy::needless_borrow)]\n");
        rust_code.push_str("#![allow(clippy::never_loop)]\n");
        rust_code.push_str("#![allow(clippy::useless_vec)]\n");
        rust_code.push_str("#![allow(clippy::collapsible_if)]\n");
        rust_code.push_str("#![allow(clippy::len_zero)]\n");
        rust_code.push_str("#![allow(unused_mut)]\n");
        rust_code.push_str("#[allow(unused_imports)]\n");
        rust_code.push_str("use corvo_lang::type_system::Value;\n");
        rust_code.push_str("use corvo_lang::RuntimeState;\n");
        rust_code.push_str("use corvo_lang::CorvoError;\n");
        rust_code.push_str("use corvo_lang::ast::AssertKind;\n");
        rust_code.push_str("use corvo_lang::*;\n");
        rust_code.push_str("use std::collections::HashMap;\n\n");

        rust_code.push_str("fn main() {\n");
        rust_code.push_str("    match run() {\n");
        rust_code.push_str("        Ok(_) => {},\n");
        rust_code.push_str("        Err(e) => {\n");
        rust_code.push_str("            eprintln!(\"{}\", e);\n");
        rust_code.push_str("            std::process::exit(e.exit_code());\n");
        rust_code.push_str("        }\n");
        rust_code.push_str("    }\n");
        rust_code.push_str("}\n\n");

        rust_code.push_str("fn run() -> Result<(), CorvoError> {\n");
        rust_code.push_str("    let mut state = RuntimeState::new();\n");
        rust_code.push_str("    state.set_script_argv(std::env::args().skip(1).collect());\n\n");

        // Embed statics
        if !self.captured_statics.is_empty() {
            rust_code.push_str("    // Statics captured during pre-execution\n");
            for (k, v) in &self.captured_statics {
                rust_code.push_str(&format!(
                    "    state.static_set(\"{}\".to_string(), {});\n",
                    k,
                    self.value_to_rust_literal(v)
                ));
            }
            rust_code.push('\n');
        }

        for stmt in &program.statements {
            rust_code.push_str(&self.transpile_stmt(stmt, "state"));
        }

        rust_code.push_str("    Ok(())\n");
        rust_code.push_str("}\n");
        rust_code
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    // skipcq: RS-R1000
    fn transpile_stmt(&mut self, stmt: &Stmt, state_var: &str) -> String {
        let mut code = String::new();
        match stmt {
            Stmt::VarSet { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!("{}    let val = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), val);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::StaticSet { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!("{}    let val = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    {}.static_set(\"{}\".to_string(), val);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarIndexSet { name, index, value } => {
                let idx_expr = self.transpile_expr(index, state_var);
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let index = {};\n", self.indent(), idx_expr));
                code.push_str(&format!(
                    "{}    let new_val = {};\n",
                    self.indent(),
                    val_expr
                ));
                code.push_str(&format!(
                    "{}    let updated = match (&current, &index) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Map(map), Value::String(key)) => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let mut new_map = map.clone();\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            new_map.insert(key.clone(), new_val);\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            Value::Map(new_map)\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        (Value::List(list), Value::Number(idx)) => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let mut new_list = list.clone();\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let i = *idx as usize;\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            if i >= new_list.len() {{ return Err(CorvoError::runtime(\"Index out of bounds\")); }}\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            new_list[i] = new_val;\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            Value::List(new_list)\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"Invalid index set\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarAddAssign { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let rhs = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    let updated = match (current, rhs) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Number(a), Value::Number(b)) => Value::Number(a + b),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        (Value::String(a), Value::String(b)) => Value::String(format!(\"{{}}{{}}\", a, b)),\n", self.indent()));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"+= fails\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarSubAssign { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let rhs = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    let updated = match (current, rhs) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Number(a), Value::Number(b)) => Value::Number(a - b),\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"-= fails\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarOrAssign { name, candidates } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let mut current = {}.var_get(\"{}\").unwrap_or(Value::Null);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!(
                    "{}    'or_assign: {{ if !current.is_truthy() {{\n",
                    self.indent()
                ));
                self.indent_level += 2;
                for cand in candidates {
                    let cand_expr = self.transpile_expr(cand, state_var);
                    code.push_str(&format!("{}let val = {};\n", self.indent(), cand_expr));
                    code.push_str(&format!("{}if val.is_truthy() {{\n", self.indent()));
                    code.push_str(&format!(
                        "{}    {}.var_set(\"{}\".to_string(), val.clone());\n",
                        self.indent(),
                        state_var,
                        name
                    ));
                    code.push_str(&format!("{}    current = val;\n", self.indent()));
                    code.push_str(&format!("{}    break 'or_assign;\n", self.indent()));
                    code.push_str(&format!("{}}}\n", self.indent()));
                }
                self.indent_level -= 2;
                code.push_str(&format!("{}    }} }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::ExprStmt { expr } => {
                let expr_code = self.transpile_expr(expr, state_var);
                code.push_str(&format!("{}{};\n", self.indent(), expr_code));
            }
            Stmt::Loop { body } => {
                code.push_str(&format!("{}loop {{\n", self.indent()));
                self.indent_level += 1;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 1;
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Browse {
                iterable,
                key,
                value,
                body,
            } => {
                let iter_expr = self.transpile_expr(iterable, state_var);
                code.push_str(&format!("{}corvo_lang::corvo_browse!(&mut {}, {}, {:?}, {:?}, {{\n", self.indent(), state_var, iter_expr, key, value));
                self.indent_level += 1;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 1;
                code.push_str(&format!("{}}});\n", self.indent()));
            }
            Stmt::Terminate => {
                if self.closure_depth > 0 {
                    code.push_str(&format!(
                        "{}        {}.var_set(\"_terminate_requested\".to_string(), Value::Boolean(true));\n",
                        self.indent(),
                        state_var
                    ));
                    code.push_str(&format!(
                        "{}        return Err(CorvoError::runtime(\"terminate\"));\n",
                        self.indent()
                    ));
                } else {
                    code.push_str(&format!("{}return Ok(());\n", self.indent()));
                }
            }
            Stmt::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let cond_c = self.transpile_expr(condition, state_var);
                code.push_str(&format!(
                    "{}if {}.as_bool().unwrap_or(false) {{\n",
                    self.indent(),
                    cond_c
                ));
                self.indent_level += 1;
                for s in then_branch {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 1;
                if !else_branch.is_empty() {
                    code.push_str(&format!("{}}} else {{\n", self.indent()));
                    self.indent_level += 1;
                    for s in else_branch {
                        code.push_str(&self.transpile_stmt(s, state_var));
                    }
                    self.indent_level -= 1;
                }
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::TryBlock { body, fallbacks } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let mut result = (|| -> Result<(), CorvoError> {{\n",
                    self.indent()
                ));
                self.indent_level += 2;
                self.closure_depth += 1;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                code.push_str(&format!("{}Ok(())\n", self.indent()));
                self.closure_depth -= 1;
                self.indent_level -= 2;
                code.push_str(&format!("{}    }})();\n", self.indent()));
                code.push_str(&format!("{}    if {}.var_get(\"_terminate_requested\").unwrap_or(Value::Boolean(false)).is_truthy() {{\n", self.indent(), state_var));
                if self.closure_depth > 0 {
                    code.push_str(&format!("{}        return Err(CorvoError::runtime(\"terminate\"));\n", self.indent()));
                } else {
                    code.push_str(&format!("{}        {}.var_set(\"_terminate_requested\".to_string(), Value::Boolean(false));\n", self.indent(), state_var));
                    code.push_str(&format!("{}        return Ok(());\n", self.indent()));
                }
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}    if result.is_err() {{\n", self.indent()));
                self.indent_level += 1;
                for fb in fallbacks {
                    code.push_str(&format!(
                        "{}result = (|| -> Result<(), CorvoError> {{\n",
                        self.indent()
                    ));
                    self.indent_level += 1;
                    self.closure_depth += 1;
                    for s in &fb.body {
                        code.push_str(&self.transpile_stmt(s, state_var));
                    }
                    code.push_str(&format!("{}Ok(())\n", self.indent()));
                    self.closure_depth -= 1;
                    self.indent_level -= 1;
                    code.push_str(&format!("{}    }})();\n", self.indent()));
                    code.push_str(&format!("{}    if {}.var_get(\"_terminate_requested\").unwrap_or(Value::Boolean(false)).is_truthy() {{\n", self.indent(), state_var));
                    if self.closure_depth > 0 {
                        code.push_str(&format!("{}        return Err(CorvoError::runtime(\"terminate\"));\n", self.indent()));
                    } else {
                        code.push_str(&format!("{}        {}.var_set(\"_terminate_requested\".to_string(), Value::Boolean(false));\n", self.indent(), state_var));
                        code.push_str(&format!("{}        return Ok(());\n", self.indent()));
                    }
                    code.push_str(&format!("{}    }}\n", self.indent()));
                    code.push_str(&format!(
                        "{}    if result.is_ok() {{ /* break fallback loop */ }}\n",
                        self.indent()
                    ));
                }
                self.indent_level -= 1;
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Assert { kind, args } => {
                if args.len() == 2 {
                    let v0 = self.transpile_expr(&args[0], state_var);
                    let v1 = self.transpile_expr(&args[1], state_var);
                    let kind_str = match kind {
                        AssertKind::Eq => "eq",
                        AssertKind::Neq => "neq",
                        AssertKind::Gt => "gt",
                        AssertKind::Lt => "lt",
                        AssertKind::Ge => "ge",
                        AssertKind::Le => "le",
                        AssertKind::Match => "match",
                    };
                    code.push_str(&format!("{}corvo_lang::corvo_assert!({}, {}, {});\n", self.indent(), kind_str, v0, v1));
                } else {
                    code.push_str(&format!("{}return Err(CorvoError::assertion(\"assert requires exactly 2 arguments\".to_string()));\n", self.indent()));
                }
            }
            Stmt::DontPanic { body } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let _res = (|| -> Result<(), CorvoError> {{\n",
                    self.indent()
                ));
                self.indent_level += 2;
                self.closure_depth += 1;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                code.push_str(&format!("{}Ok(())\n", self.indent()));
                self.closure_depth -= 1;
                self.indent_level -= 2;
                code.push_str(&format!("{}    }})();\n", self.indent()));
                code.push_str(&format!("{}    if {}.var_get(\"_terminate_requested\").unwrap_or(Value::Boolean(false)).is_truthy() {{\n", self.indent(), state_var));
                if self.closure_depth > 0 {
                    code.push_str(&format!("{}        return Err(CorvoError::runtime(\"terminate\"));\n", self.indent()));
                } else {
                    code.push_str(&format!("{}        {}.var_set(\"_terminate_requested\".to_string(), Value::Boolean(false));\n", self.indent(), state_var));
                    code.push_str(&format!("{}        return Ok(());\n", self.indent()));
                }
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::PrepBlock { .. } => {
                // Prep blocks are evaluated at compile time, so we skip them here.
            }
            Stmt::AsyncBrowse {
                list,
                proc_name,
                item_param,
                shared_vars,
            } => {
                let list_expr = self.transpile_expr(list, state_var);
                let shared_list = shared_vars
                    .iter()
                    .map(|v| format!("{:?}.to_string()", v))
                    .collect::<Vec<_>>()
                    .join(", ");
                code.push_str(&format!(
                    "{}corvo_lang::compiler::Evaluator::new().exec_async_browse_native(\n\
                     {}    match {} {{ Value::List(l) => l, _ => return Err(CorvoError::r#type(\"async_browse requires a list\")) }},\n\
                     {}    match {}.var_get({:?})? {{ Value::NativeProcedure {{ params: ref p, .. }} => p.clone(), _ => return Err(CorvoError::r#type(\"async_browse expects a procedure\")) }},\n\
                     {}    match {}.var_get({:?})? {{ Value::NativeProcedure {{ callback: ref p, .. }} => p.clone(), _ => return Err(CorvoError::r#type(\"async_browse expects a procedure\")) }},\n\
                     {}    {:?},\n\
                     {}    &[{}],\n\
                     {}    &mut {}\n\
                     {})?;\n",
                    self.indent(),
                    self.indent(),
                    list_expr,
                    self.indent(),
                    state_var,
                    proc_name,
                    self.indent(),
                    state_var,
                    proc_name,
                    self.indent(),
                    item_param,
                    self.indent(),
                    shared_list,
                    self.indent(),
                    state_var,
                    self.indent()
                ));
            }
            Stmt::HttpListen {
                port,
                req_ident,
                resp_ident,
                shared_vars,
                body,
            } => {
                let port_expr = self.transpile_expr(port, state_var);
                let shared_list = shared_vars
                    .iter()
                    .map(|v| format!("{:?}.to_string()", v))
                    .collect::<Vec<_>>()
                    .join(", ");
                let old_indent = self.indent_level;
                self.indent_level += 2;
                self.closure_depth += 1;
                let mut body_code: String = body
                    .iter()
                    .map(|s| self.transpile_stmt(s, state_var))
                    .collect();
                body_code.push_str(&format!("{}Ok(Value::Null)\n", self.indent()));
                self.closure_depth -= 1;
                self.indent_level = old_indent;
                code.push_str(&format!(
                    "{}corvo_lang::compiler::Evaluator::new().exec_http_listen_native(\n\
                     {}    {},\n\
                     {}    {:?},\n\
                     {}    {:?},\n\
                     {}    &[{}],\n\
                     {}    std::sync::Arc::new(move |_args, {}| {{\n\
                     {}\
                     {}    }}),\n\
                     {}    &mut {}\n\
                     {})?;\n",
                    self.indent(),
                    self.indent(),
                    port_expr,
                    self.indent(),
                    req_ident,
                    self.indent(),
                    resp_ident,
                    self.indent(),
                    shared_list,
                    self.indent(),
                    state_var,
                    body_code,
                    self.indent(),
                    self.indent(),
                    state_var,
                    self.indent()
                ));
            }
            Stmt::AmqpConsume {
                connection,
                queue,
                msg_ident,
                shared_vars,
                body,
            } => {
                let conn_expr = self.transpile_expr(connection, state_var);
                let queue_expr = self.transpile_expr(queue, state_var);
                let shared_list = shared_vars
                    .iter()
                    .map(|v| format!("{:?}", v))
                    .collect::<Vec<_>>()
                    .join(", ");
                let old_indent = self.indent_level;
                self.indent_level += 2;
                self.closure_depth += 1;
                let mut body_code: String = body
                    .iter()
                    .map(|s| self.transpile_stmt(s, state_var))
                    .collect();
                body_code.push_str(&format!("{}Ok(())\n", self.indent()));
                self.closure_depth -= 1;
                self.indent_level = old_indent;
                code.push_str(&format!(
                    "{}corvo_lang::compiler::Evaluator::new().exec_amqp_consume_native(\n\
                     {}    {},\n\
                     {}    {},\n\
                     {}    {:?},\n\
                     {}    &[{}],\n\
                     {}    std::sync::Arc::new(move |{}| {{\n\
                     {}\
                     {}    }}),\n\
                     {}    &mut {}\n\
                     {})?;\n",
                    self.indent(),
                    self.indent(),
                    conn_expr,
                    self.indent(),
                    queue_expr,
                    self.indent(),
                    msg_ident,
                    self.indent(),
                    shared_list,
                    self.indent(),
                    state_var,
                    body_code,
                    self.indent(),
                    self.indent(),
                    state_var,
                    self.indent()
                ));
            }
        }
        code
    }

    fn transpile_expr(&mut self, expr: &Expr, state_var: &str) -> String {
        match expr {
            Expr::Literal { value } => self.value_to_rust_literal(value),
            Expr::VarGet { name } => format!("{}.var_get(\"{}\")?", state_var, name),
            Expr::StaticGet { name } => format!("{}.static_get(\"{}\")?", state_var, name),
            Expr::Binary { op, left, right } => {
                let l = self.transpile_expr(left, state_var);
                match op {
                    BinaryOp::And => format!(
                        "(if {}.as_bool().unwrap_or(false) {{ Value::Boolean({}.as_bool().unwrap_or(false)) }} else {{ Value::Boolean(false) }})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Or => format!(
                        "(if {}.as_bool().unwrap_or(false) {{ Value::Boolean(true) }} else {{ Value::Boolean({}.as_bool().unwrap_or(false)) }})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Eq => format!(
                        "Value::Boolean({} == {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Neq => format!(
                        "Value::Boolean({} != {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Lt => format!(
                        "Value::Boolean({} < {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Le => format!(
                        "Value::Boolean({} <= {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Gt => format!(
                        "Value::Boolean({} > {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    BinaryOp::Ge => format!(
                        "Value::Boolean({} >= {})",
                        l,
                        self.transpile_expr(right, state_var)
                    ),
                    _ => {
                        let r = self.transpile_expr(right, state_var);
                        if *op == BinaryOp::Add {
                            format!(
                                "match ({}, {}) {{ (Value::Number(a), Value::Number(b)) => Value::Number(a + b), (Value::String(a), Value::String(b)) => Value::String(format!(\"{{}}{{}}\", a, b)), _ => return Err(CorvoError::r#type(\"Arithmetic error\")) }}",
                                l, r
                            )
                        } else {
                            let op_str = match op {
                                BinaryOp::Sub => "-",
                                BinaryOp::Mul => "*",
                                BinaryOp::Div => "/",
                                BinaryOp::Mod => "%",
                                _ => unreachable!(),
                            };
                            format!(
                                "match ({}, {}) {{ (Value::Number(a), Value::Number(b)) => Value::Number(a {} b), _ => return Err(CorvoError::r#type(\"Arithmetic error\")) }}",
                                l, r, op_str
                            )
                        }
                    }
                }
            }
            Expr::Unary { op, operand } => {
                let v = self.transpile_expr(operand, state_var);
                match op {
                    UnaryOp::Neg => format!("match {} {{ Value::Number(n) => Value::Number(-n), _ => return Err(CorvoError::r#type(\"Negation error\")) }}", v),
                    UnaryOp::Not => format!("Value::Boolean(!{}.as_bool().unwrap_or(false))", v),
                }
            }
            Expr::StringInterpolation { parts } => {
                let mut p_codes = Vec::new();
                for p in parts {
                    p_codes.push(self.transpile_expr(p, state_var));
                }
                format!(
                    "Value::String(format!(\"{}\", {}))",
                    "{}".repeat(parts.len()),
                    p_codes.join(", ")
                )
            }
            Expr::FunctionCall {
                name,
                args,
                named_args,
            } => {
                let args_list: Vec<String> = args
                    .iter()
                    .map(|a| self.transpile_expr(a, state_var))
                    .collect();
                let mut named_map_items = Vec::new();
                for (k, v) in named_args {
                    named_map_items.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.transpile_expr(v, state_var)
                    ));
                }
                let named_map_code = if named_map_items.is_empty() {
                    "HashMap::new()".to_string()
                } else {
                    format!("HashMap::from([{}])", named_map_items.join(", "))
                };
                if name == "__list__" {
                    format!("Value::List(vec![{}])", args_list.join(", "))
                } else if name == "__map__" {
                    format!("Value::Map({})", named_map_code)
                } else {
                    let macro_name = name.replace('.', "_");
                    let args_str = if args_list.is_empty() {
                        String::new()
                    } else {
                        format!(", {}", args_list.join(", "))
                    };
                    if named_map_items.is_empty() {
                        format!("{}!(&{}{})?", macro_name, state_var, args_str)
                    } else {
                        format!(
                            "{}!(&{}; kwargs: {}{})?",
                            macro_name, state_var, named_map_code, args_str
                        )
                    }
                }
            }
            Expr::MethodCall {
                target,
                method,
                args,
                named_args,
            } => {
                let target_code = self.transpile_expr(target, state_var);
                let args_list: Vec<String> = args
                    .iter()
                    .map(|a| self.transpile_expr(a, state_var))
                    .collect();
                let mut named_map_items = Vec::new();
                for (k, v) in named_args {
                    named_map_items.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.transpile_expr(v, state_var)
                    ));
                }
                let _named_map_code = if named_map_items.is_empty() {
                    "HashMap::new()".to_string()
                } else {
                    format!("HashMap::from([{}])", named_map_items.join(", "))
                };

                let mut outer_names_code = Vec::new();
                for a in args {
                    if let Expr::VarGet { name } = a {
                        outer_names_code.push(format!("Some({:?}.to_string())", name));
                    } else {
                        outer_names_code.push("None".to_string());
                    }
                }
                let outer_names_list = outer_names_code.join(", ");

                format!(
                    "corvo_lang::corvo_method_call!(&mut {}, {}, {:?}, vec![{}], vec![{}] as Vec<Option<String>>)",
                    state_var,
                    target_code,
                    method,
                    args_list.join(", "),
                    outer_names_list
                )
            }
            Expr::Match { value, arms } => {
                let val_code = self.transpile_expr(value, state_var);
                let mut arms_code = Vec::new();
                for arm in arms {
                    let condition = match &arm.pattern {
                        MatchPattern::Literal(v) => format!("_match_val == {}", self.value_to_rust_literal(v)),
                        MatchPattern::Wildcard => "true".to_string(),
                        MatchPattern::Regex(p, f) => {
                            format!(
                                "if let Value::String(text) = &_match_val {{ standard_lib::re::build_regex({:?}, {:?}).map(|r| r.is_match(text)).unwrap_or(false) }} else {{ false }}",
                                p, f
                            )
                        }
                    };
                    arms_code.push(format!(
                        "if {} {{\n    {}\n}}",
                        condition,
                        self.transpile_expr(&arm.body, state_var)
                    ));
                }
                format!(
                    "{{\n    let _match_val = {};\n    {} else {{\n        Value::Null\n    }}\n}}",
                    val_code,
                    arms_code.join(" else ")
                )
            }
            Expr::IndexAccess { target, index } => {
                let t = self.transpile_expr(target, state_var);
                let i = self.transpile_expr(index, state_var);
                format!("corvo_lang::corvo_index!({}, {})", t, i)
            }
            Expr::SliceAccess { target, start, end } => {
                let t = self.transpile_expr(target, state_var);
                let s = match start {
                    Some(e) => format!(
                        "Some({}.as_number().unwrap_or(0.0) as usize)",
                        self.transpile_expr(e, state_var)
                    ),
                    None => "None".to_string(),
                };
                let e = match end {
                    Some(e) => format!(
                        "Some({}.as_number().unwrap_or(0.0) as usize)",
                        self.transpile_expr(e, state_var)
                    ),
                    None => "None".to_string(),
                };
                format!("corvo_lang::corvo_slice!({}, {}, {})", t, s, e)
            }
            Expr::ProcedureLiteral { params, body } => {
                let mut proc_code = String::new();
                proc_code.push_str("Value::NativeProcedure {\n");
                proc_code.push_str(&format!(
                    "    params: vec![{}],\n",
                    params
                        .iter()
                        .map(|p| format!("{:?}.to_string()", p))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                proc_code.push_str(
                    "    callback: std::sync::Arc::new(|args: &[Value], mut state: &mut RuntimeState| {\n",
                );

                // Bind parameters
                proc_code.push_str(&format!("    if args.len() < {} {{ return Err(CorvoError::runtime(format!(\"Procedure expects at least {} arguments, got {{}}\", args.len()))); }}\n", params.len(), params.len()));
                for (i, p) in params.iter().enumerate() {
                    proc_code.push_str(&format!(
                        "    state.var_set(\"{}\".to_string(), args[{}].clone());\n",
                        p, i
                    ));
                }

                // Transpile body
                let mut sub_transpiler = Transpiler {
                    indent_level: 1,
                    captured_statics: self.captured_statics.clone(),
                    closure_depth: self.closure_depth + 1,
                };
                for stmt in body {
                    proc_code.push_str(&sub_transpiler.transpile_stmt(stmt, "state"));
                }

                proc_code.push_str("    Ok(Value::Null)\n");
                proc_code.push_str("}),\n}");
                proc_code
            }
            _ => "Value::Null".to_string(),
        }
    }

    fn value_to_rust_literal(&self, value: &Value) -> String {
        match value {
            Value::Null => "Value::Null".to_string(),
            Value::Boolean(b) => format!("Value::Boolean({})", b),
            Value::Number(n) => format!("Value::Number({:?})", n),
            Value::String(s) => format!("Value::String({:?}.to_string())", s),
            Value::List(items) => {
                let inner: Vec<String> = items
                    .iter()
                    .map(|v| self.value_to_rust_literal(v))
                    .collect();
                format!("Value::List(vec![{}])", inner.join(", "))
            }
            Value::Map(m) => {
                let mut entries = Vec::new();
                for (k, v) in m {
                    entries.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.value_to_rust_literal(v)
                    ));
                }
                format!("Value::Map(HashMap::from([{}]))", entries.join(", "))
            }
            Value::Regex(p, f) => format!("Value::Regex({:?}.to_string(), {:?}.to_string())", p, f),
            Value::NativeProcedure { params, .. } => {
                let p_expr = params
                    .iter()
                    .map(|p| format!("{:?}.to_string()", p))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "Value::NativeProcedure {{ params: vec![{}], callback: std::sync::Arc::new(|_, _| Ok(Value::Null)) }}",
                    p_expr
                )
            }
            _ => "Value::Null".to_string(),
        }
    }
}
